services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gym
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gym-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - gym-network
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 20s

  activemq:
    image: rmohr/activemq
    container_name: activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - gym-network

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - gym-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      gym-crm-service:
        condition: service_started
      training-hours-tracker:
        condition: service_started
    restart: always
    networks:
      - gym-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - R2DBC_URL=r2dbc:pool:mysql://mysql-db:3306/gym
      - DB_USERNAME=root
      - DB_PASSWORD=root

  gym-crm-service:
    build: ./gym-crm-service
    container_name: gym-crm-service
    env_file:
      - ./gym-crm-service/.env
    depends_on:
      mysql-db:
        condition: service_healthy
      activemq:
        condition: service_started
      discovery-server:
        condition: service_started
    networks:
      - gym-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - STG_DB_URL=jdbc:mysql://mysql-db:3306/gym
      - DB_URL=jdbc:mysql://mysql-db:3306/gym
      - STG_BROKER_URL=tcp://activemq:61616
      - DB_USERNAME=root
      - DB_PASSWORD=root

  training-hours-tracker:
    build: ./training-hours-tracker
    container_name: training-hours-tracker
    env_file:
      - ./training-hours-tracker/.env
    depends_on:
      mongo-db:
        condition: service_healthy
      activemq:
        condition: service_started
      discovery-server:
        condition: service_started
    networks:
      - gym-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/gym
      - STG_BROKER_URL=tcp://activemq:61616

networks:
  gym-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data: