server:
  port: 8080
  max-http-header-size: 65536

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        maxHeaderSize: 65536
      routes:
        - id: gym-crm-service-route
          uri: lb://gym-crm-service
          predicates:
             - Path=/api/v1/gym-crm-service/**
        - id: training-hours-tracker-route
          uri: lb://training-hours-tracker
          predicates:
            - Path=/api/v1/training-hours-tracker/**
          filters:
            - AddRequestHeader=Authorization, $httpAuthorization
        - id: actuator-route
          uri: lb://gym-crm-service
          predicates:
            - Path=/actuator/**
  r2dbc:
    url: r2dbc:mysql://localhost:3306/gym
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    flyway:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  file:
    name: app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg [transactionId=%X{X-Transaction-Id}]%n"
  appender:
    console:
      name: STDOUT
jwt:
  secret: my-secure-secret-key-which-is-shared
gateway:
  secret: my-secure-gateway-secret-key-which-is-shared