server:
  port: 8091
spring:
  application:
    name: gym-automation-service
  config:
    import: optional:file:.env[.properties]
  security:
    enabled: false
  data:
    mongodb:
      uri: ${TEST_MONGO_URL}
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    enabled: false
  cloud:
    discovery:
      enabled: false
    gateway:
      enabled: false
crm:
  service:
    port: 8099
hoursTracker:
  service:
    port: 8098