server:
  port: 8091
spring:
  application:
    name: gym-automation-service
  security:
    enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/gym-test
  datasource:
    url: jdbc:mysql://localhost:3306/gym_test_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    enabled: false
  cloud:
    discovery:
      enabled: false
    gateway:
      enabled: false
crm:
  service:
    port: 8099
hoursTracker:
  service:
    port: 8098