spring:
  application:
    name: gym-crm-service
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: stg
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        jpa:
          show_sql: true
        hbm2ddl:
          auto: none
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
  cloud:
    discovery:
      reactive:
        discoveryClient:
          simple:
            instances:
              training-hours-tracker:
                - uri: http://localhost:8084
api:
  version: /api/v1/gym-crm-service
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api/v1/gym-crm-service/swagger-ui.html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  file:
    name: app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg [transactionId=%X{X-Transaction-Id}]%n"
  appender:
    console:
      name: STDOUT
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8080' ]
app:
  root:
    url: http://localhost:8080
jwt:
  secret: my-secure-secret-key-which-is-shared
gateway:
  secret: my-secure-gateway-secret-key-which-is-shared