server:
  port: 8099
spring:
  application:
    name: gym-crm-service
  config:
    activate:
      on-profile: autotest
    import: optional:file:.env[.properties]
  liquibase:
    enabled: false
    change-log: classpath:/liquibase/db.changelog-master.xml
  cloud:
    discovery:
      enabled: false
    gateway:
      enabled: false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jpa:
          show_sql: true
        hbm2ddl:
          auto: create
  instance:
    prefer-ip-address: true
gateway:
  secret: my-secure-gateway-secret-key-which-is-shared
jwt:
  secret: my-secure-secret-key-which-is-shared
app:
  root:
    url: http://localhost:8080
api:
  version: /api/v1/gym-crm-service
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api/v1/gym-crm-service/swagger-ui.html
jsm:
  queue:
    destination: training-hours-queue-test