spring:
  config:
    activate:
      on-profile: prod
  activemq:
    broker-url: ${PROD_BROKER_URL}
    user: ${PROD_USER}
    password: ${PROD_PASSWORD}
    packages:
      trust-all: true
server:
  port: 8089
logging:
  level:
    root: WARN