spring:
  config:
    activate:
      on-profile: stg
  activemq:
    broker-url: ${STG_BROKER_URL}
    user: ${STG_USER}
    password: ${STG_PASSWORD}
    packages:
      trust-all: true
server:
  port: 8086
logging:
  level:
    root: INFO