spring:
  application:
    name: training-hours-tracker
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:trainersdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password
    jpa:
      hibernate:
        ddl-auto: update
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
api:
  version: /api/v1/training-hours-tracker
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api/v1/training-hours-tracker/swagger-ui.html
logging:
  level:
    root: INFO
  file:
    name: app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg [transactionId=%X{X-Transaction-Id}]%n"
  appender:
    console:
      name: STDOUT
app:
  analytic_username: temp
  analytic_password: temp
jwt:
  secret: my-secure-secret-key-which-is-shared