spring:
  config:
    activate:
      on-profile: dev
  activemq:
    broker-url: ${DEV_BROKER_URL}
    user: ${DEV_USER}
    password: ${DEV_PASSWORD}
    packages:
      trust-all: true
server:
  port: 8087
logging:
  level:
    root: DEBUG