spring:
  config:
    activate:
      on-profile: local
  activemq:
    broker-url: ${LOCAL_BROKER_URL}
    user: ${LOCAL_USER}
    password: ${LOCAL_PASSWORD}
    packages:
      trust-all: true
server:
  port: 8088
logging:
  level:
    root: DEBUG